
import { Inter } from 'next/font/google';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',    
});

import Providers from "@/components/Providers";
import Navbar from "@/components/layout/Navbar";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased px-3 sm:px-6 lg:px-12 `}
      >
        <Providers>
        <Navbar/>
          {children}
          
        </Providers>
      </body>
    </html>
  );
}
